/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantSlugRouteImport } from './routes/$tenantSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantSlugIndexRouteImport } from './routes/$tenantSlug/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as TenantSlugSettingsRouteImport } from './routes/$tenantSlug/settings'
import { Route as TenantSlugMySignupsRouteImport } from './routes/$tenantSlug/my-signups'
import { Route as TenantSlugOpportunitiesIndexRouteImport } from './routes/$tenantSlug/opportunities/index'
import { Route as TenantSlugManageIndexRouteImport } from './routes/$tenantSlug/manage/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as TenantSlugOpportunitiesNewRouteImport } from './routes/$tenantSlug/opportunities/new'
import { Route as TenantSlugOpportunitiesOpportunityIdRouteImport } from './routes/$tenantSlug/opportunities/$opportunityId'
import { Route as TenantSlugManageMembersRouteImport } from './routes/$tenantSlug/manage/members'
import { Route as TenantSlugManageApplicationsRouteImport } from './routes/$tenantSlug/manage/applications'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const TenantSlugRoute = TenantSlugRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugIndexRoute = TenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantSlugRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugSettingsRoute = TenantSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TenantSlugRoute,
} as any)
const TenantSlugMySignupsRoute = TenantSlugMySignupsRouteImport.update({
  id: '/my-signups',
  path: '/my-signups',
  getParentRoute: () => TenantSlugRoute,
} as any)
const TenantSlugOpportunitiesIndexRoute =
  TenantSlugOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => TenantSlugRoute,
  } as any)
const TenantSlugManageIndexRoute = TenantSlugManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => TenantSlugRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugOpportunitiesNewRoute =
  TenantSlugOpportunitiesNewRouteImport.update({
    id: '/opportunities/new',
    path: '/opportunities/new',
    getParentRoute: () => TenantSlugRoute,
  } as any)
const TenantSlugOpportunitiesOpportunityIdRoute =
  TenantSlugOpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => TenantSlugRoute,
  } as any)
const TenantSlugManageMembersRoute = TenantSlugManageMembersRouteImport.update({
  id: '/manage/members',
  path: '/manage/members',
  getParentRoute: () => TenantSlugRoute,
} as any)
const TenantSlugManageApplicationsRoute =
  TenantSlugManageApplicationsRouteImport.update({
    id: '/manage/applications',
    path: '/manage/applications',
    getParentRoute: () => TenantSlugRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteWithChildren
  '/$tenantSlug/my-signups': typeof TenantSlugMySignupsRoute
  '/$tenantSlug/settings': typeof TenantSlugSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/$tenantSlug/manage/applications': typeof TenantSlugManageApplicationsRoute
  '/$tenantSlug/manage/members': typeof TenantSlugManageMembersRoute
  '/$tenantSlug/opportunities/$opportunityId': typeof TenantSlugOpportunitiesOpportunityIdRoute
  '/$tenantSlug/opportunities/new': typeof TenantSlugOpportunitiesNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/$tenantSlug/manage': typeof TenantSlugManageIndexRoute
  '/$tenantSlug/opportunities': typeof TenantSlugOpportunitiesIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tenantSlug/my-signups': typeof TenantSlugMySignupsRoute
  '/$tenantSlug/settings': typeof TenantSlugSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
  '/$tenantSlug/manage/applications': typeof TenantSlugManageApplicationsRoute
  '/$tenantSlug/manage/members': typeof TenantSlugManageMembersRoute
  '/$tenantSlug/opportunities/$opportunityId': typeof TenantSlugOpportunitiesOpportunityIdRoute
  '/$tenantSlug/opportunities/new': typeof TenantSlugOpportunitiesNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/$tenantSlug/manage': typeof TenantSlugManageIndexRoute
  '/$tenantSlug/opportunities': typeof TenantSlugOpportunitiesIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteWithChildren
  '/$tenantSlug/my-signups': typeof TenantSlugMySignupsRoute
  '/$tenantSlug/settings': typeof TenantSlugSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/$tenantSlug/manage/applications': typeof TenantSlugManageApplicationsRoute
  '/$tenantSlug/manage/members': typeof TenantSlugManageMembersRoute
  '/$tenantSlug/opportunities/$opportunityId': typeof TenantSlugOpportunitiesOpportunityIdRoute
  '/$tenantSlug/opportunities/new': typeof TenantSlugOpportunitiesNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/$tenantSlug/manage/': typeof TenantSlugManageIndexRoute
  '/$tenantSlug/opportunities/': typeof TenantSlugOpportunitiesIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenantSlug'
    | '/$tenantSlug/my-signups'
    | '/$tenantSlug/settings'
    | '/api/$'
    | '/demo/clerk'
    | '/demo/orpc-todo'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/$tenantSlug/'
    | '/$tenantSlug/manage/applications'
    | '/$tenantSlug/manage/members'
    | '/$tenantSlug/opportunities/$opportunityId'
    | '/$tenantSlug/opportunities/new'
    | '/api/rpc/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/$tenantSlug/manage'
    | '/$tenantSlug/opportunities'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$tenantSlug/my-signups'
    | '/$tenantSlug/settings'
    | '/api/$'
    | '/demo/clerk'
    | '/demo/orpc-todo'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/$tenantSlug'
    | '/$tenantSlug/manage/applications'
    | '/$tenantSlug/manage/members'
    | '/$tenantSlug/opportunities/$opportunityId'
    | '/$tenantSlug/opportunities/new'
    | '/api/rpc/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/$tenantSlug/manage'
    | '/$tenantSlug/opportunities'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/$tenantSlug'
    | '/$tenantSlug/my-signups'
    | '/$tenantSlug/settings'
    | '/api/$'
    | '/demo/clerk'
    | '/demo/orpc-todo'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/$tenantSlug/'
    | '/$tenantSlug/manage/applications'
    | '/$tenantSlug/manage/members'
    | '/$tenantSlug/opportunities/$opportunityId'
    | '/$tenantSlug/opportunities/new'
    | '/api/rpc/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/$tenantSlug/manage/'
    | '/$tenantSlug/opportunities/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantSlugRoute: typeof TenantSlugRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$tenantSlug': {
      id: '/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug'
      preLoaderRoute: typeof TenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/': {
      id: '/$tenantSlug/'
      path: '/'
      fullPath: '/$tenantSlug/'
      preLoaderRoute: typeof TenantSlugIndexRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/settings': {
      id: '/$tenantSlug/settings'
      path: '/settings'
      fullPath: '/$tenantSlug/settings'
      preLoaderRoute: typeof TenantSlugSettingsRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/$tenantSlug/my-signups': {
      id: '/$tenantSlug/my-signups'
      path: '/my-signups'
      fullPath: '/$tenantSlug/my-signups'
      preLoaderRoute: typeof TenantSlugMySignupsRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/$tenantSlug/opportunities/': {
      id: '/$tenantSlug/opportunities/'
      path: '/opportunities'
      fullPath: '/$tenantSlug/opportunities'
      preLoaderRoute: typeof TenantSlugOpportunitiesIndexRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/$tenantSlug/manage/': {
      id: '/$tenantSlug/manage/'
      path: '/manage'
      fullPath: '/$tenantSlug/manage'
      preLoaderRoute: typeof TenantSlugManageIndexRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/opportunities/new': {
      id: '/$tenantSlug/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/$tenantSlug/opportunities/new'
      preLoaderRoute: typeof TenantSlugOpportunitiesNewRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/$tenantSlug/opportunities/$opportunityId': {
      id: '/$tenantSlug/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/$tenantSlug/opportunities/$opportunityId'
      preLoaderRoute: typeof TenantSlugOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/$tenantSlug/manage/members': {
      id: '/$tenantSlug/manage/members'
      path: '/manage/members'
      fullPath: '/$tenantSlug/manage/members'
      preLoaderRoute: typeof TenantSlugManageMembersRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/$tenantSlug/manage/applications': {
      id: '/$tenantSlug/manage/applications'
      path: '/manage/applications'
      fullPath: '/$tenantSlug/manage/applications'
      preLoaderRoute: typeof TenantSlugManageApplicationsRouteImport
      parentRoute: typeof TenantSlugRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TenantSlugRouteChildren {
  TenantSlugMySignupsRoute: typeof TenantSlugMySignupsRoute
  TenantSlugSettingsRoute: typeof TenantSlugSettingsRoute
  TenantSlugIndexRoute: typeof TenantSlugIndexRoute
  TenantSlugManageApplicationsRoute: typeof TenantSlugManageApplicationsRoute
  TenantSlugManageMembersRoute: typeof TenantSlugManageMembersRoute
  TenantSlugOpportunitiesOpportunityIdRoute: typeof TenantSlugOpportunitiesOpportunityIdRoute
  TenantSlugOpportunitiesNewRoute: typeof TenantSlugOpportunitiesNewRoute
  TenantSlugManageIndexRoute: typeof TenantSlugManageIndexRoute
  TenantSlugOpportunitiesIndexRoute: typeof TenantSlugOpportunitiesIndexRoute
}

const TenantSlugRouteChildren: TenantSlugRouteChildren = {
  TenantSlugMySignupsRoute: TenantSlugMySignupsRoute,
  TenantSlugSettingsRoute: TenantSlugSettingsRoute,
  TenantSlugIndexRoute: TenantSlugIndexRoute,
  TenantSlugManageApplicationsRoute: TenantSlugManageApplicationsRoute,
  TenantSlugManageMembersRoute: TenantSlugManageMembersRoute,
  TenantSlugOpportunitiesOpportunityIdRoute:
    TenantSlugOpportunitiesOpportunityIdRoute,
  TenantSlugOpportunitiesNewRoute: TenantSlugOpportunitiesNewRoute,
  TenantSlugManageIndexRoute: TenantSlugManageIndexRoute,
  TenantSlugOpportunitiesIndexRoute: TenantSlugOpportunitiesIndexRoute,
}

const TenantSlugRouteWithChildren = TenantSlugRoute._addFileChildren(
  TenantSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantSlugRoute: TenantSlugRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
